### ISSUE TITLE
For talking about Project1

### ISSUE THREAD

**Issue by gyoung19** [gyoung19/AI#5]
Testing, testing, 1 ,2 ,3.

**Comment by jyterencekim** [comment]
So the new one is just a variant of `cornersHeuristic_twoPointEstimate`. (I have just made this into the main heuristic. The previous one may not also be consistent, although it seems to perform better in the given test cases).
I am not sure of the consistency of "two point estimation", although I feel it should be consistent.
Specifically, I am not sure about the correctness of my assumption: I assumed that the cost of the optimal path must be greater than or equal to straight_line_distance(currentPosition, nearestFood) + straight_line_distance(nearestFood, one of the remaining food pieces that is farthest from nearestFood).

**Comment by gyoung19** [comment]
The optimal path for any of these mazes should be a continuous path from the starting point through all pellets in the maze that retraces steps as few times as possible. To be consistent, the heuristic estimate has to be always less than the total path from any node to the goal for any node. I think this heuristic fulfills that requirement since the straight line distance starting from the closest food to the farthest food will approximate the optimal path under ideal conditions (maze is a straight line from nearest to farthest food with no turns, walls, corners, etc) and be less than the optimal path under all other conditions (if there is any deviation from the straight line the optimal path will take longer than the straight line estimate). I do not forsee any scenarios where this heuristic could produce a result greater than the optimal path. Does this sound right?

**Comment by gyoung19** [comment]
Added some code that satisfies the autograder for Q8, take a look and let me know if you think anything needs revision there.

**Comment by jyterencekim** [comment]
Seems perfectly fine. Thanks!
